## Notebook

# NumPy

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

### Arreglos

In [6]:
arr = np.array([1,2,3])

print(arr)

[1 2 3]


In [8]:
arr = np.array(([1,2,3], [4,5,6]))

print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
arr = np.array([1,2,3,4,5,6], ndmin=3)

print (arr.ndim)

print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0][0][0])


3
[[[1 2 3 4 5 6]]]
[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
1


In [15]:
arr = np.zeros((2,2))

print (arr)

[[0. 0.]
 [0. 0.]]


In [20]:
arr = np.ones((3,3))

print (arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
arr = np.random.rand(3,3)

print (arr)

[[0.95941059 0.08899603 0.95904716]
 [0.22010185 0.32978365 0.14573814]
 [0.50103086 0.15984478 0.23173881]]


### Opraciones

In [22]:
arr1 = [1,2,3]

arr2 = [4,5,6]

arr3= np.add(arr1, arr2)

print(arr3)

[5 7 9]


In [26]:
arr1 = [1,2,3]

arr2 = [4,5,6]

arr3= np.subtract(arr2, arr1)

print(arr3)

[3 3 3]


In [28]:
arr1 = [1,2,3]

arr2 = [4,5,6]

arr3= np.multiply(arr1, arr2)

print(arr3)

[ 4 10 18]


In [30]:
arr1 = [1,2,3]

arr2 = [4,5,6]

arr3= np.divide(arr1, arr2)

print(arr3)

[0.25 0.4  0.5 ]


### Agrefacion

In [34]:
arr= ([3,5,4])

media = np.mean(arr)

print(media)

4.0


In [35]:
arr =([3,5,4])

mediana = np.median(arr)

print(mediana)

4.0


In [36]:
arr =([3, 5, 4])

maximo = np.max(arr)

print(maximo)

5


In [38]:
arr =([3, 5, 4])

minimo = np.min(arr)

print(minimo)

3


### Indexacion

In [45]:
arr = np.array([1,2,3,4,5,6])

print (arr[0])

1


In [46]:
arr = np.array([1,2,3,4,5,6])

print(arr[-1])

6


In [48]:
arr = np.array(([1,2,3], [4,5,6]))

print (arr[0, 2])

3


### Slicing

In [51]:
arr = np.array([1,2,3,4,5,6])

print(arr [1:4])

[2 3 4]


In [54]:
arr = np.array([1,2,3,4,5,6])

print(arr[1:6:2])

[2 4 6]


In [57]:
arr = np.array([1,2,3,4,5,6])

print(arr[::3])

[1 4]
